plot(Resistores$V, Resistores$X47, xlab = "ddp (V)", ylab = "Corrente (mA)", col="blue", main = "Resistor 47 ohms")
abline(lm(Resistores$X47 ~Resistores$V), col="red")
plot(Resistores$V, Resistores$X100, xlab = "ddp (V)", ylab = "Corrente (mA)", col="blue", main = "Resistor 100 ohms")
abline(lm(Resistores$X100 ~ Resistores$V), col="red")
plot(Resistores$V, Resistores$X200, xlab = "ddp (V)", ylab = "Corrente (mA)", col="blue", main = "Resistor 200 ohms")
abline(lm(Resistores$X200 ~ Resistores$V), col="red")
plot(Resistores$V, Resistores$X2k, xlab = "ddp (V)", ylab = "Corrente (mA)", col="blue", main = "Resistor 2k ohms")
abline(lm( Resistores$X2k ~ Resistores$V), col="red")
plot(Resistores$V, Resistores$X560k, xlab = "ddp (V)", ylab = "Corrente (pA)", col="blue", main = "Resistor 560k ohms")
abline(lm(Resistores$X560k ~ Resistores$V), col="red")
